# Generated by Django 3.2.12 on 2022-05-12 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosConservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadoConservacion', models.CharField(max_length=30)),
                ('estadoIntegridad', models.CharField(max_length=30)),
                ('detalle', models.CharField(max_length=30)),
                ('tratamiento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DatosLocalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=3, max_digits=8)),
                ('longitud', models.DecimalField(decimal_places=3, max_digits=8)),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DatosProcedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaGeografica', models.CharField(max_length=30)),
                ('denominacion', models.CharField(max_length=30)),
                ('excavacion', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaAdquisicion', models.CharField(max_length=30)),
                ('propietario', models.CharField(max_length=30)),
                ('tipoDocumento', models.CharField(max_length=30)),
                ('numeroDocumento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=30)),
                ('tipoBien', models.CharField(max_length=30)),
                ('demoninacion', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('autoria', models.IntegerField(null=True)),
                ('lugarManufactura', models.CharField(max_length=30)),
                ('estilo', models.CharField(max_length=30)),
                ('datacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Datación')),
                ('valorCultural', models.CharField(max_length=30)),
                ('otrosCodigos', models.CharField(max_length=30)),
                ('observaciones', models.CharField(max_length=30)),
                ('posicion', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2 '), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=20)),
                ('datosConservacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.datosconservacion', verbose_name='Datos de Conservación')),
                ('datosLocalizacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.datoslocalizacion', verbose_name='Datos de Localización')),
                ('datosProcedencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.datosprocedencia', verbose_name='Datos de Procedencia')),
                ('datosPropiedad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.datospropiedad', verbose_name='Datos de Propiedad')),
            ],
        ),
    ]
