# Generated by Django 3.2.12 on 2022-05-23 19:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloDemoninacion', models.CharField(max_length=30)),
                ('datacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='datacion')),
                ('observaciones', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('tipoPatrimonio', models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2 '), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2)),
                ('categoria', models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2 '), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2)),
                ('subcategoria', models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2 '), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2)),
                ('estado', models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2 '), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2)),
                ('gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
