# Generated by Django 3.2.12 on 2022-05-12 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('largo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('espesor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fondo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diametro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='patrimoniocultural',
            name='datosConservacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.datosconservacion', verbose_name='Datos de Conservación'),
        ),
        migrations.AlterField(
            model_name='patrimoniocultural',
            name='datosLocalizacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.datoslocalizacion', verbose_name='Datos de Localización'),
        ),
        migrations.AlterField(
            model_name='patrimoniocultural',
            name='datosProcedencia',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.datosprocedencia', verbose_name='Datos de Procedencia'),
        ),
        migrations.AlterField(
            model_name='patrimoniocultural',
            name='datosPropiedad',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.datospropiedad', verbose_name='Datos de Propiedad'),
        ),
        migrations.CreateModel(
            name='ElementoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=30)),
                ('integridad', models.CharField(max_length=30)),
                ('conservacion', models.CharField(max_length=30)),
                ('dimensiones', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.dimensiones', verbose_name='Dimensiones Elemento Adicional')),
                ('patrimonioCultural', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.patrimoniocultural', verbose_name='Patrimonio Cultural')),
            ],
        ),
        migrations.CreateModel(
            name='DatosTecnicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialPrincipal', models.CharField(max_length=30)),
                ('materialSecundario', models.CharField(max_length=30)),
                ('tManufactura', models.CharField(max_length=30)),
                ('tDecoracion', models.CharField(max_length=30)),
                ('tAcabado', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('dimensiones', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.dimensiones', verbose_name='Dimensiones Patrimonio Cultural')),
            ],
        ),
        migrations.AddField(
            model_name='patrimoniocultural',
            name='datosTecnicos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.datostecnicos', verbose_name='Datos Técnicos'),
        ),
    ]
