# Generated by Django 3.2.12 on 2022-05-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadTuristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
                ('tipo', models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2 '), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaApertura', models.TimeField(auto_now_add=True)),
                ('horaCierre', models.TimeField(auto_now_add=True)),
                ('actividades', models.ManyToManyField(to='patrimonios.ActividadTuristica')),
                ('entradas', models.ManyToManyField(to='patrimonios.Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('doi', models.CharField(blank=True, max_length=12, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2),
        ),
        migrations.CreateModel(
            name='ServicioPorPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterial')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='PropietarioPorPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
                ('Patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.propietario')),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioMaterialMueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('patrimoniomaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterial')),
            ],
        ),
        migrations.AddField(
            model_name='patrimoniomaterial',
            name='patrimonio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio'),
        ),
        migrations.AddField(
            model_name='patrimoniomaterial',
            name='servicios',
            field=models.ManyToManyField(to='patrimonios.Servicio'),
        ),
        migrations.CreateModel(
            name='EntradaPorPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.entrada')),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadTuristicaPorPatrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
                ('actividadTuristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.actividadturistica')),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterial')),
            ],
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.institucion'),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='propietarios',
            field=models.ManyToManyField(to='patrimonios.Propietario'),
        ),
    ]
