# Generated by Django 3.2.12 on 2022-05-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0002_auto_20220523_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaporpatrimonio',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='entradaporpatrimonio',
            name='patrimonio',
        ),
        migrations.RemoveField(
            model_name='propietarioporpatrimonio',
            name='Patrimonio',
        ),
        migrations.RemoveField(
            model_name='propietarioporpatrimonio',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='servicioporpatrimonio',
            name='patrimonio',
        ),
        migrations.RemoveField(
            model_name='servicioporpatrimonio',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='patrimoniomaterialmueble',
            name='patrimoniomaterial',
        ),
        migrations.AddField(
            model_name='entrada',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='patrimonioMaterial',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterial'),
        ),
        migrations.AlterField(
            model_name='patrimoniomaterialmueble',
            name='alto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='patrimoniomaterialmueble',
            name='ancho',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='patrimoniomaterialmueble',
            name='largo',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='ActividadTuristicaPorPatrimonio',
        ),
        migrations.DeleteModel(
            name='EntradaPorPatrimonio',
        ),
        migrations.DeleteModel(
            name='PropietarioPorPatrimonio',
        ),
        migrations.DeleteModel(
            name='ServicioPorPatrimonio',
        ),
    ]
