# Generated by Django 3.2.12 on 2022-05-12 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0002_auto_20220512_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablecimientoCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
                ('latitud', models.DecimalField(decimal_places=3, max_digits=8)),
                ('longitud', models.DecimalField(decimal_places=3, max_digits=8)),
                ('direccion', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='patrimoniocultural',
            name='establecimientoCultural',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrimonios.establecimientocultural', verbose_name='Establecimiento Cultural'),
        ),
    ]
