# Generated by Django 3.2.12 on 2022-05-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0003_auto_20220528_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniomaterialmueble',
            name='patrimonioMaterial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterial'),
        ),
    ]
