# Generated by Django 3.2.12 on 2022-05-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0004_alter_patrimoniomaterialmueble_patrimoniomaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patrimonio',
            old_name='observaciones',
            new_name='observacion',
        ),
    ]
