# Generated by Django 3.2.12 on 2022-05-28 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0005_rename_observaciones_patrimonio_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrimonioValoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=60)),
                ('correo', models.CharField(default='', max_length=60)),
                ('valoracion', models.IntegerField(default=0)),
                ('comentario', models.CharField(default='', max_length=250)),
                ('estado', models.CharField(choices=[('1', 'Pendiente'), ('2', 'Aceptado')], default='1', max_length=2)),
                ('patrimonio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio')),
            ],
        ),
    ]
