# Generated by Django 3.2.12 on 2022-06-07 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0006_patrimoniovaloracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='patrimonio',
            old_name='tituloDemoninacion',
            new_name='nombreTituloDemoninacion',
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='datacion',
        ),
        migrations.RemoveField(
            model_name='patrimonio',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='actividadturistica',
            name='categoria',
            field=models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2 '), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='actividadturistica',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actividadturistica',
            name='patrimonio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='patrimonio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='codigo',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='descripcion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='distrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='tipo',
            field=models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2 '), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2 '), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='servicio',
            name='observacion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='patrimonio',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2 '), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2),
        ),
        migrations.CreateModel(
            name='PatrimonioMaterialInMueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2'), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2)),
                ('subtipo', models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2'), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2)),
                ('particularidades', models.CharField(blank=True, max_length=200, null=True)),
                ('tipoIngreso', models.CharField(choices=[('1', 'Gratuito'), ('2', 'Pagado'), ('3', 'Estado 3'), ('4', 'No información')], default='1', max_length=2)),
                ('estadoActual', models.CharField(max_length=200)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio')),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioInMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2'), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2)),
                ('subtipo', models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2'), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2)),
                ('particularidades', models.CharField(blank=True, max_length=200, null=True)),
                ('tipoIngreso', models.CharField(choices=[('1', 'Gratuito'), ('2', 'Pagado'), ('3', 'Estado 3'), ('4', 'No información')], default='1', max_length=2)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio')),
            ],
        ),
        migrations.CreateModel(
            name='FuenteBibliografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio')),
            ],
        ),
        migrations.CreateModel(
            name='EpocaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epocaPropicia', models.CharField(blank=True, max_length=100, null=True)),
                ('especificacion', models.CharField(blank=True, max_length=100, null=True)),
                ('horaVisita', models.TimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
                ('patrimonioMaterialInMueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterialinmueble')),
            ],
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='responsables',
            field=models.ManyToManyField(to='patrimonios.Responsable'),
        ),
    ]
