# Generated by Django 3.2.12 on 2022-06-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0008_alter_actividadturistica_patrimonio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('material', models.CharField(max_length=100, null=True)),
                ('integridad', models.CharField(max_length=100, null=True)),
                ('conservacion', models.CharField(max_length=100, null=True)),
                ('alto', models.FloatField(default=0.0)),
                ('largo', models.FloatField(default=0.0)),
                ('ancho', models.FloatField(default=0.0)),
                ('espesor', models.FloatField(default=0.0)),
                ('fondo', models.FloatField(default=0.0)),
                ('diametro', models.FloatField(default=0.0)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Excavacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaGeografica', models.CharField(max_length=100, null=True)),
                ('clasificacionOrigen', models.CharField(max_length=100, null=True)),
                ('nombreClasificacion', models.CharField(max_length=100, null=True)),
                ('capa', models.CharField(max_length=100, null=True)),
                ('unidad', models.CharField(max_length=100, null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSecundario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioArqueologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, null=True)),
                ('tipoMaterial', models.CharField(max_length=100, null=True)),
                ('cultura', models.CharField(max_length=50, null=True)),
                ('estilo', models.CharField(max_length=100, null=True)),
                ('periodo', models.CharField(max_length=100, null=True)),
                ('diametroMax', models.FloatField(default=0.0, null=True)),
                ('diametroMin', models.FloatField(default=0.0, null=True)),
                ('diametroBase', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioEtnografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filacionCultural', models.CharField(max_length=50, null=True)),
                ('procedencia', models.CharField(max_length=50, null=True)),
                ('datacion', models.CharField(max_length=100, null=True)),
                ('materialSoporte', models.CharField(max_length=100, null=True)),
                ('fondo', models.FloatField(default=0.0)),
                ('diametro', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioHistoricoArtistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100, null=True)),
                ('estilo', models.CharField(max_length=100, null=True)),
                ('procedencia', models.CharField(max_length=100, null=True)),
                ('datacion', models.CharField(max_length=100, null=True)),
                ('materialSoporte', models.CharField(max_length=100, null=True)),
                ('fondo', models.FloatField(default=0.0)),
                ('diametro', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioIndustrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeloMarca', models.CharField(max_length=50, null=True)),
                ('serie', models.CharField(max_length=50, null=True)),
                ('fabricante', models.CharField(max_length=200, null=True)),
                ('procedencia', models.CharField(max_length=50, null=True)),
                ('datacion', models.CharField(max_length=50, null=True)),
                ('materialSoporte', models.CharField(max_length=100, null=True)),
                ('fondo', models.FloatField(default=0.0)),
                ('diametro', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PatrimonioPaleontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCientifico', models.CharField(max_length=100, null=True)),
                ('reino', models.CharField(max_length=50, null=True)),
                ('phylumDivision', models.CharField(max_length=50, null=True)),
                ('clase', models.CharField(max_length=50, null=True)),
                ('eraGeologica', models.CharField(max_length=50, null=True)),
                ('epocaGeologica', models.CharField(max_length=50, null=True)),
                ('tipoFosilizacion', models.CharField(max_length=50, null=True)),
                ('tipoMuestra', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TecnicaAcabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TecnicaDecoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TecnicaManufactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='patrimoniomaterialmueble',
            name='patrimonioMaterial',
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='asociacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='codigoInventario',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='codigoPropietario',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='codigoRegistroAnteriorINC',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='conservacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='detalleConservacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='detalleTratamiento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='espesor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='formaAdquisicion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='integridad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='nroRegistro',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='otrosCodigos',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='patrimonio',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio'),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='situacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='tipo',
            field=models.CharField(choices=[('1', 'Estado 1'), ('2', 'Estado 2'), ('3', 'Estado 3'), ('4', 'Estado 4')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='ubicacionEspecifica',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='PatrimonioMaterial',
        ),
        migrations.AddField(
            model_name='patrimoniopaleontologico',
            name='patrimonioMueble',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterialmueble'),
        ),
        migrations.AddField(
            model_name='patrimonioindustrial',
            name='patrimonioMueble',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterialmueble'),
        ),
        migrations.AddField(
            model_name='patrimoniohistoricoartistico',
            name='patrimonioMueble',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterialmueble'),
        ),
        migrations.AddField(
            model_name='patrimonioetnografico',
            name='patrimonioMueble',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterialmueble'),
        ),
        migrations.AddField(
            model_name='patrimonioarqueologico',
            name='patrimonioMueble',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterialmueble'),
        ),
        migrations.AddField(
            model_name='excavacion',
            name='patrimonioMueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterialmueble'),
        ),
        migrations.AddField(
            model_name='elementoadicional',
            name='patrimonioMueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimoniomaterialmueble'),
        ),
    ]
