# Generated by Django 3.2.12 on 2022-06-07 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0009_auto_20220607_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniomaterialmueble',
            name='patrimonio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio'),
        ),
    ]
