# Generated by Django 3.2.12 on 2022-06-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0010_alter_patrimoniomaterialmueble_patrimonio'),
    ]

    operations = [
        migrations.AddField(
            model_name='excavacion',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='materialesSecundarios',
            field=models.ManyToManyField(to='patrimonios.MaterialSecundario'),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='tecnicasAcabado',
            field=models.ManyToManyField(to='patrimonios.TecnicaAcabado'),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='tecnicasDecoracion',
            field=models.ManyToManyField(to='patrimonios.TecnicaDecoracion'),
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='tecnicasManifactura',
            field=models.ManyToManyField(to='patrimonios.TecnicaManufactura'),
        ),
    ]
