# Generated by Django 3.2.12 on 2022-06-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0011_auto_20220607_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadturistica',
            name='categoria',
            field=models.CharField(choices=[('1', 'Categoría 1'), ('2', 'Categoría 2 '), ('3', 'Categoría 3'), ('4', 'Categoría 4')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='actividadturistica',
            name='tipo',
            field=models.CharField(choices=[('1', 'Tipo 1'), ('2', 'Tipo 2'), ('3', 'Tipo 3'), ('4', 'Tipo 4')], default='1', max_length=2),
        ),
    ]
