# Generated by Django 3.2.12 on 2022-06-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincul_app', '0002_alter_documento_url'),
        ('patrimonios', '0012_auto_20220609_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='documentos',
            field=models.ManyToManyField(to='mincul_app.Documento'),
        ),
    ]
