# Generated by Django 3.2.12 on 2022-06-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0013_propietario_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimonio',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='patrimonio',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
