# Generated by Django 3.2.12 on 2022-06-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0015_institucion_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='campo',
        ),
    ]
