# Generated by Django 3.2.12 on 2022-06-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0014_auto_20220612_2050'),
        ('patrimonios', '0015_auto_20220611_1923'),
    ]

    operations = [
    ]
