# Generated by Django 3.2.12 on 2022-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0016_remove_institucion_campo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='categoria',
            field=models.CharField(choices=[('1', 'Sitios Naturales'), ('2', 'Manifestaciones Culturales'), ('3', 'Realizaciones Técnicas, Científicas y Artísticas Contemporáneas'), ('4', 'Folclore'), ('5', 'Acontecimientos Programados'), ('6', 'Arqueológico'), ('7', 'Histórico-Artístico'), ('8', 'Etnográfico'), ('9', 'Plaeontológico'), ('10', 'Industrial')], default='1', max_length=2),
        ),
    ]
