# Generated by Django 3.2.12 on 2022-06-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0016_merge_0014_auto_20220612_2050_0015_auto_20220611_1923'),
        ('patrimonios', '0017_alter_patrimonio_categoria'),
    ]

    operations = [
    ]
