# Generated by Django 3.2.12 on 2022-06-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0018_merge_20220615_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('1', 'Inmaterial 1'), ('2', 'Material Inmueble'), ('3', 'Material Mueble')], max_length=2)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='tipoPatrimonio',
            field=models.CharField(choices=[('1', 'Inmaterial 1'), ('2', 'Material Inmueble'), ('3', 'Material Mueble')], default='1', max_length=2),
        ),
    ]
