# Generated by Django 3.2.12 on 2022-06-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0020_auto_20220616_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonioinmaterial',
            name='tipoIngreso',
            field=models.CharField(choices=[('1', 'Gratuito'), ('2', 'Pagado'), ('3', 'No información')], default='1', max_length=2),
        ),
    ]
