# Generated by Django 3.2.12 on 2022-06-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0023_alter_patrimoniovaloracion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
