# Generated by Django 3.2.12 on 2022-06-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0028_institucion_direccion'),
        ('patrimonios', '0028_institucion_direccion'),
    ]

    operations = [
    ]
