# Generated by Django 3.2.12 on 2022-06-19 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0029_merge_20220616_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoGeografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('1', 'Patrimonio'), ('2', 'Institucion')], max_length=2)),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.institucion')),
                ('patrimonio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio')),
            ],
        ),
    ]
