# Generated by Django 3.2.12 on 2022-06-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0031_auto_20220619_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonioinmaterial',
            name='subtipo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioinmaterial',
            name='tipoInmaterial',
            field=models.CharField(choices=[('1', 'Artístico'), ('2', 'Eventos'), ('3', 'Fiestas'), ('4', 'Artesanía y Artes'), ('5', 'Creencias Populares'), ('6', 'Ferias y Mercados'), ('7', 'Gastronomía'), ('8', 'Músicas y Danzas')], default='1', max_length=2),
        ),
    ]
