# Generated by Django 3.2.12 on 2022-06-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0032_auto_20220619_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='descripcion',
            field=models.CharField(max_length=4000),
        ),
    ]
