# Generated by Django 3.2.12 on 2022-06-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0034_alter_patrimonio_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='observacion',
            field=models.CharField(max_length=500),
        ),
    ]
