# Generated by Django 3.2.12 on 2022-06-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0036_alter_patrimonio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
