# Generated by Django 3.2.12 on 2022-06-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0037_alter_patrimonio_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimoniovaloracion',
            name='patrimonio',
        ),
        migrations.AddField(
            model_name='patrimoniovaloracion',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.puntogeografico'),
        ),
    ]
