# Generated by Django 3.2.12 on 2022-06-22 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0022_merge_20220616_1819'),
        ('patrimonios', '0039_institucion_url'),
    ]

    operations = [
    ]
