# Generated by Django 3.2.12 on 2022-06-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0040_auto_20220622_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patrimoniomaterialinmueble',
            old_name='tipo',
            new_name='tipoInmueble',
        ),
        migrations.RemoveField(
            model_name='patrimoniomaterialinmueble',
            name='subtipo',
        ),
        migrations.AlterField(
            model_name='epocavisita',
            name='horaVisita',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
