# Generated by Django 3.2.12 on 2022-06-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0041_auto_20220622_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrimoniomaterialinmueble',
            name='subtipo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioinmaterial',
            name='tipoIngreso',
            field=models.CharField(choices=[('1', 'Libre'), ('2', 'Pagado'), ('3', 'Semi-restringido'), ('4', 'Restringido'), ('5', 'No información')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='patrimoniomaterialinmueble',
            name='tipoIngreso',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patrimoniomaterialinmueble',
            name='tipoInmueble',
            field=models.CharField(choices=[('1', 'Arquitectura y Espacios Urbanos'), ('2', 'Lugares Históricos'), ('3', 'Museos y otros'), ('4', 'Pueblos'), ('5', 'Sitios Arqueológicos'), ('6', 'Centros Científicos y Técnicos'), ('7', 'Explotaciones Industriales'), ('8', 'Explotaciones Mineras'), ('9', 'Caídas de agua'), ('10', 'Cavidades naturales'), ('11', 'Costas'), ('12', 'Zonas paisajísticas'), ('13', 'a. Montañas'), ('14', 'b. Planicies'), ('15', 'c. Valles'), ('16', 'd. Quebradas'), ('17', 'e. Cañones'), ('18', 'g. Cuerpo de Agua'), ('19', 'j. Manantiales'), ('20', 'n. Áreas Protegidas'), ('21', 'o. Otros')], default='1', max_length=2),
        ),
    ]
