# Generated by Django 3.2.12 on 2022-06-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0042_auto_20220622_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniomaterialinmueble',
            name='tipoIngreso',
            field=models.CharField(choices=[('1', 'Libre'), ('2', 'Pagado'), ('3', 'Semi-restringido'), ('4', 'Restringido'), ('5', 'No información')], default='1', max_length=2),
        ),
    ]
