# Generated by Django 3.2.12 on 2022-06-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0043_alter_patrimoniomaterialinmueble_tipoingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniomaterialinmueble',
            name='tipoIngreso',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
