# Generated by Django 3.2.12 on 2022-06-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0044_alter_patrimoniomaterialinmueble_tipoingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadturistica',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='actividadturistica',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patrimoniomaterialinmueble',
            name='estadoActual',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='observacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
