# Generated by Django 3.2.12 on 2022-06-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0046_alter_fuentebibliografica_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='nombreTituloDemoninacion',
            field=models.CharField(max_length=200),
        ),
    ]
