# Generated by Django 3.2.12 on 2022-06-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0047_alter_patrimonio_nombretitulodemoninacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonio',
            name='long',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioinmaterial',
            name='particularidades',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
