# Generated by Django 3.2.12 on 2022-06-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0050_alter_patrimoniomaterialinmueble_particularidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniomaterialinmueble',
            name='particularidades',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
