# Generated by Django 3.2.12 on 2022-06-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0052_alter_patrimoniomaterialinmueble_estadoactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniomaterialinmueble',
            name='estadoActual',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
