# Generated by Django 3.2.12 on 2022-06-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0053_alter_patrimoniomaterialinmueble_estadoactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonio',
            name='observacion',
            field=models.CharField(max_length=1000),
        ),
    ]
