# Generated by Django 3.2.12 on 2022-06-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0054_alter_patrimonio_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
