# Generated by Django 3.2.12 on 2022-06-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0056_alter_patrimonio_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuentebibliografica',
            name='referencia',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
