# Generated by Django 3.2.12 on 2022-06-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0057_alter_fuentebibliografica_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='long',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
    ]
