# Generated by Django 3.2.12 on 2022-06-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0058_auto_20220623_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuentebibliografica',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
