# Generated by Django 3.2.12 on 2022-06-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0060_alter_fuentebibliografica_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epocavisita',
            name='epocaPropicia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='epocavisita',
            name='especificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
