# Generated by Django 3.2.12 on 2022-06-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0064_alter_patrimoniomaterialinmueble_particularidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniomaterialinmueble',
            name='estadoActual',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
