# Generated by Django 3.2.12 on 2022-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0066_auto_20220623_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='long',
            field=models.DecimalField(decimal_places=7, max_digits=16, null=True),
        ),
    ]
