# Generated by Django 3.2.12 on 2022-06-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0067_auto_20220623_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonioinmaterial',
            name='particularidades',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioinmaterial',
            name='tipoIngreso',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
