# Generated by Django 3.2.12 on 2022-06-24 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0040_merge_0022_merge_20220616_1819_0039_institucion_url'),
        ('patrimonios', '0068_auto_20220623_0224'),
    ]

    operations = [
    ]
