# Generated by Django 3.2.12 on 2022-06-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0068_auto_20220623_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='patrimonioindustrial',
            name='fabricante',
        ),
        migrations.AddField(
            model_name='patrimonioindustrial',
            name='fabricantes',
            field=models.ManyToManyField(to='patrimonios.Fabricante'),
        ),
    ]
