# Generated by Django 3.2.12 on 2022-06-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0069_auto_20220625_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimoniomaterialmueble',
            name='tipo',
        ),
        migrations.AddField(
            model_name='patrimoniomaterialmueble',
            name='tipoBien',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
