# Generated by Django 3.2.12 on 2022-06-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0071_auto_20220626_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='doi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='tipo',
            field=models.CharField(choices=[('1', 'Jurídica'), ('2', 'Natural')], default='1', max_length=2),
        ),
    ]
