# Generated by Django 3.2.12 on 2022-06-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0072_auto_20220626_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimoniomaterialmueble',
            name='alto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patrimoniomaterialmueble',
            name='ancho',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patrimoniomaterialmueble',
            name='espesor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patrimoniomaterialmueble',
            name='largo',
            field=models.CharField(max_length=50),
        ),
    ]
