# Generated by Django 3.2.12 on 2022-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0073_auto_20220626_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonioarqueologico',
            name='diametroBase',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioarqueologico',
            name='diametroMax',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioarqueologico',
            name='diametroMin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
