# Generated by Django 3.2.12 on 2022-06-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0076_auto_20220626_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonioindustrial',
            name='diametro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patrimonioindustrial',
            name='fondo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
