# Generated by Django 3.2.12 on 2022-06-27 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0069_merge_20220623_1927'),
        ('patrimonios', '0077_auto_20220626_1509'),
    ]

    operations = [
    ]
