# Generated by Django 3.2.12 on 2022-06-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0078_merge_20220626_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='direccion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
