# Generated by Django 3.2.12 on 2022-06-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincul_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='url',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='archive/'),
        ),
    ]
