# Generated by Django 3.2.12 on 2022-05-23 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patrimonios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoConservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='fechaInicio')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='fechaFin')),
                ('tipoProyecto', models.CharField(max_length=50)),
                ('estado', models.CharField(blank=True, choices=[('1', 'Preventivo'), ('2', 'Correctivo')], default='1', max_length=2, null=True)),
                ('patrimonios', models.ManyToManyField(to='patrimonios.Patrimonio')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
