# Generated by Django 3.2.12 on 2022-05-23 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conservacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='fechaInicio')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='fechaFin')),
                ('presupuesto', models.FloatField()),
                ('gastoTotal', models.FloatField()),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
                ('conservadores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('materiales', models.CharField(blank=True, max_length=200, null=True)),
                ('herramientas', models.CharField(blank=True, max_length=200, null=True)),
                ('indumentaria', models.CharField(blank=True, max_length=200, null=True)),
                ('gasto', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('fechaRegistro', models.DateField(blank=True, null=True, verbose_name='fechaRegistro')),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservacion.actividad')),
                ('conservador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documentos', models.ManyToManyField(to='conservacion.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPorTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservacion.documento')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservacion.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPorActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservacion.actividad')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservacion.documento')),
            ],
        ),
        migrations.CreateModel(
            name='ConservadorPorActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservacion.actividad')),
                ('conservador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('contenido', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conservacion.documento')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservacion.tarea')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='documentos',
            field=models.ManyToManyField(to='conservacion.Documento'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='patrimonio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservacion.proyectoconservacion'),
        ),
    ]
