# Generated by Django 3.2.12 on 2022-05-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mincul_app', '0001_initial'),
        ('conservacion', '0005_auto_20220528_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='documentos1',
        ),
        migrations.AddField(
            model_name='tarea',
            name='documentos',
            field=models.ManyToManyField(related_name='documentosTarea', through='conservacion.DocumentoPorTarea', to='mincul_app.Documento'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservacion.proyectoconservacion'),
        ),
        migrations.AlterField(
            model_name='documentoportarea',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mincul_app.documento'),
        ),
        migrations.AlterField(
            model_name='documentoportarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conservacion.tarea'),
        ),
    ]
