# Generated by Django 4.0.4 on 2022-05-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0006_auto_20220528_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='actividadPrecia',
            field=models.ManyToManyField(blank=True, to='conservacion.actividad'),
        ),
    ]
