# Generated by Django 3.2.12 on 2022-05-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0007_alter_actividad_actividadprecia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='actividadPrecia',
            field=models.ManyToManyField(blank=True, related_name='_conservacion_actividad_actividadPrecia_+', to='conservacion.Actividad'),
        ),
    ]
