# Generated by Django 3.2.12 on 2022-06-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0010_alter_actividad_actividadprecia'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoconservacion',
            name='cantidadAct',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectoconservacion',
            name='cantidadActR',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='proyectoconservacion',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'En Proceso'), ('1', 'Pendiente'), ('2', 'Completado')], default='0', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='proyectoconservacion',
            name='tipoProyecto',
            field=models.CharField(blank=True, choices=[('0', 'Preventivo'), ('1', 'Correctivo'), ('2', 'Curativo')], default='0', max_length=2, null=True),
        ),
    ]
