# Generated by Django 3.2.12 on 2022-06-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0012_auto_20220607_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
