# Generated by Django 3.2.12 on 2022-06-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0013_actividad_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'En Proceso'), ('1', 'Registrado'), ('2', 'Completado')], default='0', max_length=2, null=True),
        ),
    ]
