# Generated by Django 3.2.12 on 2022-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0014_actividad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoconservacion',
            name='codigo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
