# Generated by Django 3.2.12 on 2022-06-11 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conservacion', '0015_alter_proyectoconservacion_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='conservador',
        ),
        migrations.AddField(
            model_name='campo',
            name='conservador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
