# Generated by Django 3.2.12 on 2022-06-11 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conservacion', '0016_auto_20220611_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='conservador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
