# Generated by Django 3.2.12 on 2022-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0017_alter_campo_conservador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='presupuesto',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
