# Generated by Django 3.2.12 on 2022-06-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0018_tarea_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'En Proceso'), ('1', 'Registrado'), ('2', 'Completado')], default='0', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='proyectoconservacion',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proyectoconservacion',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'En Proceso'), ('1', 'Registrado'), ('2', 'Completado')], default='1', max_length=2, null=True),
        ),
    ]
