# Generated by Django 3.2.12 on 2022-06-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0019_auto_20220616_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoconservacion',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
