# Generated by Django 3.2.12 on 2022-06-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0020_alter_proyectoconservacion_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoconservacion',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
