# Generated by Django 3.2.12 on 2022-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0022_tarea_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
