# Generated by Django 3.2.12 on 2022-06-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0023_tarea_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='actividadPrecia',
        ),
        migrations.AddField(
            model_name='actividad',
            name='relaciones',
            field=models.ManyToManyField(blank=True, related_name='_conservacion_actividad_relaciones_+', to='conservacion.Actividad'),
        ),
    ]
