# Generated by Django 3.2.12 on 2022-06-25 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0026_alter_tarea_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='conservador',
        ),
    ]
