# Generated by Django 3.2.12 on 2022-06-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0029_auto_20220626_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Registrado'), ('1', 'En proceso'), ('2', 'Finalizado'), ('3', 'Anulada')], default='0', max_length=2, null=True),
        ),
    ]
