# Generated by Django 3.2.12 on 2022-06-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0030_alter_actividad_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='detalleObservacion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Registrada'), ('2', 'En proceso'), ('3', 'En evaluación'), ('4', 'Observada'), ('5', 'Finalizada')], default='1', max_length=2, null=True),
        ),
    ]
