# Generated by Django 3.2.12 on 2022-06-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0031_auto_20220626_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Registrada'), ('2', 'En proceso'), ('3', 'En evaluación'), ('4', 'Observada'), ('5', 'Finalizada')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True),
        ),
    ]
