# Generated by Django 3.2.12 on 2022-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0032_auto_20220627_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Registrada'), ('1', 'En proceso'), ('2', 'Finalizada'), ('3', 'Anulada')], default='0', max_length=2, null=True),
        ),
    ]
