# Generated by Django 3.2.12 on 2022-06-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conservacion', '0033_alter_actividad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoconservacion',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'En Proceso'), ('1', 'Registrado'), ('2', 'Completado'), ('3', 'Cancelado')], default='1', max_length=2, null=True),
        ),
    ]
