# Generated by Django 3.2.12 on 2022-05-28 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mincul_app', '0001_initial'),
        ('patrimonios', '0003_auto_20220528_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('valoracion', models.IntegerField()),
                ('comentario', models.CharField(max_length=200)),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio')),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField(blank=True, null=True, verbose_name='fechaRegistro')),
                ('fechaAprobacion', models.DateField(blank=True, null=True, verbose_name='fechaAprobacion')),
                ('prioridad', models.CharField(blank=True, choices=[('0', 'Leve'), ('1', 'Urgente')], default='1', max_length=2, null=True)),
                ('estado', models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mincul_app.documento')),
                ('patrimonio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrimonios.patrimonio')),
            ],
        ),
    ]
