# Generated by Django 3.2.12 on 2022-05-31 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mincul_app', '0001_initial'),
        ('incidente', '0002_auto_20220530_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mincul_app.documento'),
        ),
    ]
