# Generated by Django 3.2.12 on 2022-06-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincul_app', '0002_alter_documento_url'),
        ('incidente', '0004_alter_incidente_patrimonio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='incidente',
            name='correo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='documentos',
            field=models.ManyToManyField(to='mincul_app.Documento'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='fechaOcurrencia',
            field=models.DateField(blank=True, null=True, verbose_name='fechaOcurrencia'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='telefono',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipoAfectacion',
            field=models.CharField(blank=True, choices=[('0', 'Leve'), ('1', 'Urgente')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
