# Generated by Django 3.2.12 on 2022-06-18 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonios', '0024_auto_20220617_2148'),
        ('incidente', '0006_alter_incidente_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patrimonios.institucion'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='tipoIncidentado',
            field=models.CharField(blank=True, choices=[('1', 'Patrimonio'), ('2', 'Institucion')], default='1', max_length=2, null=True),
        ),
    ]
