# Generated by Django 3.2.12 on 2022-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0009_incidente_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'No Asignado'), ('2', 'Asignado')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='tipoAfectacion',
            field=models.CharField(blank=True, choices=[('1', 'Invasión/Ocupación Ilegal/Ampliación de Invasión'), ('2', 'Deterioro de patrimonio por efectos de la persona'), ('3', 'Deterioro de patrimonio por efectos de la naturaleza'), ('4', 'Destrucción en zonas arqueológicas'), ('5', 'Destrucción de casonas'), ('6', 'Huaquería'), ('7', 'Otros')], default='1', max_length=2, null=True),
        ),
    ]
