# Generated by Django 3.2.12 on 2022-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0010_auto_20220622_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Asignado')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Registrado'), ('2', 'En Proceso'), ('3', 'Resuelto'), ('4', 'Denegado')], default='1', max_length=2, null=True),
        ),
    ]
