# Generated by Django 3.2.12 on 2022-06-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidente', '0011_auto_20220625_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Inactivo')], default='1', max_length=2, null=True),
        ),
    ]
