# Generated by Django 3.2.12 on 2022-05-28 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mincul_app', '0001_initial'),
        ('traslado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doiSolicitante', models.CharField(blank=True, max_length=12, null=True)),
                ('nombreSolicitante', models.CharField(blank=True, max_length=200, null=True)),
                ('correo', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='celularSolicitante',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='correoSolicitante',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='doiRepresentante',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='doiSolicitante',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='domicilioResponsable',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='gestor',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='nombreResponsable',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='nombreSolicitante',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='numeroRNAoRNDA',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='personaEfectuaraTraslado',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='procedenciaMuestras',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='representanteLegal',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='telefonoSolicitante',
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='documentos1',
            field=models.ManyToManyField(through='traslado.DocumentoPorSolicitud', to='mincul_app.Documento'),
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='gestorPatrimonio',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='gestorPatrimonioTraslado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='nombreExposicion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='numeroResolucion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='tipoTraslado',
            field=models.CharField(blank=True, choices=[('0', 'Tipo1'), ('1', 'Tipo2')], default='1', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='ubigeoDestino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentoporsolicitud',
            name='documento',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='mincul_app.documento'),
        ),
        migrations.AlterField(
            model_name='documentoporsolicitud',
            name='solicitud',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='traslado.solicitudtraslado'),
        ),
        migrations.AlterField(
            model_name='solicitudtraslado',
            name='gestorConservacionTraslados',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='gestorConservacionTrasladosTraslado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SolicitudPorPatrimonio',
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='entidadSolicitante',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='traslado.entidadsolicitante'),
        ),
    ]
