# Generated by Django 3.2.12 on 2022-05-28 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mincul_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('traslado', '0002_auto_20220528_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='documentos1',
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='documentos',
            field=models.ManyToManyField(through='traslado.DocumentoPorSolicitud', to='mincul_app.Documento'),
        ),
        migrations.AlterField(
            model_name='documentoporsolicitud',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mincul_app.documento'),
        ),
        migrations.AlterField(
            model_name='documentoporsolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traslado.solicitudtraslado'),
        ),
        migrations.AlterField(
            model_name='solicitudtraslado',
            name='entidadSolicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traslado.entidadsolicitante'),
        ),
        migrations.AlterField(
            model_name='solicitudtraslado',
            name='gestorConservacionTraslados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestorConservacionTrasladosTraslado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudtraslado',
            name='gestorPatrimonio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestorPatrimonioTraslado', to=settings.AUTH_USER_MODEL),
        ),
    ]
