# Generated by Django 3.2.12 on 2022-06-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado', '0005_alter_solicitudtraslado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtraslado',
            name='detalleRechazo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
