# Generated by Django 3.2.12 on 2022-06-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado', '0007_auto_20220614_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='fechaRetornoProgramada',
        ),
        migrations.RemoveField(
            model_name='solicitudtraslado',
            name='fechaRetornoReal',
        ),
        migrations.AddField(
            model_name='solicitudtraslado',
            name='fechaRetorno',
            field=models.DateField(blank=True, null=True, verbose_name='fechaRetorno'),
        ),
    ]
