# Generated by Django 3.2.12 on 2022-06-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslado', '0008_auto_20220617_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtraslado',
            name='estado',
            field=models.CharField(blank=True, choices=[('1', 'Registrada'), ('2', 'En evaluación'), ('3', 'Rechazada'), ('4', 'Aprobada'), ('5', 'Ejecutada'), ('6', 'Finalizada')], default='1', max_length=2, null=True),
        ),
    ]
